### ISSUE TITLE
Cannot run from windows?

### ISSUE THREAD

**Issue by kyuhyong** [zauberzeug/odrive-gui#3]
Hello, 

On windows 11 with python version 3.11.4 installed
Odrivetool v0.5.6 is installed
pip install -r requirements.txt to meet the requirement.

When tried to run in windows with **python .\src\main.py** command, 
I get below error and blank webpage.

```
python .\src\main.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\#####\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\#####\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 129, in _main
    prepare(preparation_data)
  File "C:\Users\#####\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\#####\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "C:\workspaces\odrive\sw\odrive-gui\src\main.py", line 6, in <module>
    from nicegui import ui
  File "C:\Users\####\AppData\Local\Programs\Python\Python311\Lib\site-packages\nicegui\__init__.py", line 2, in <module>
    from nicegui.nicegui import app, ui
  File "C:\Users\####\AppData\Local\Programs\Python\Python311\Lib\site-packages\nicegui\nicegui.py", line 8, in <module>
    from .ui import Ui  # NOTE: before justpy
    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\####\AppData\Local\Programs\Python\Python311\Lib\site-packages\nicegui\ui.py", line 5, in <module>
    class Ui:
  File "C:\Users\####\AppData\Local\Programs\Python\Python311\Lib\site-packages\nicegui\ui.py", line 6, in Ui
    from .config import config  # NOTE: before run
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\####\AppData\Local\Programs\Python\Python311\Lib\site-packages\nicegui\config.py", line 47, in <module>
    with open(filepath) as f:
         ^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '<frozen runpy>'
```

Note '#####' is a username assigned to the OS

**Comment by falkoschindler** [comment]
Hi @kyuhyong! Thanks for bringing this up!

odrive-gui hasn't been updated for quite a while now. According to the requirements.txt it uses NiceGUI 0.8.4, although we're approaching version 1.3.0 there. So I guess we should update NiceGUI before investigating any OS-specific issue. Unfortunatly, I'm not sure if we'll find the time to do so shortly.

Would you be up for helping us out? If you'd update NiceGUI to the latest version, the UI might needs some tweaks here and there. But it shouldn't be too bad as odrive-gui uses pretty basic features.

**Comment by kyuhyong** [comment]
Hi @falkoschindler 
I will try to update NiceGUI and see if it works. Although I have no experience with that library if I find solution, I will commit and request for pull later! Thanks,

**Comment by falkoschindler** [comment]
Hi @kyuhyong,
We just made an update to odrive-gui that replaces NiceGUI 0.8.4 with 1.3.x. Would you like to try out the main branch and check if it resolves this issue?

**Comment by falkoschindler** [comment]
I'll close this issue for now. Feel free to create a new one if the problem persists with a new version of ODrive GUI.
